[build]
  command = "npm start"  # or your build command
  publish = "public"         # or your output directory

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200